// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Racun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KomunalneUsluge")
                        .HasColumnType("int");

                    b.Property<long>("MesecIzdavanja")
                        .HasColumnType("bigint");

                    b.Property<string>("Placen")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("StanID")
                        .HasColumnType("int");

                    b.Property<int>("Struja")
                        .HasColumnType("int");

                    b.Property<int>("Voda")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StanID");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("backend.Models.Stan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojClanova")
                        .HasColumnType("bigint");

                    b.Property<string>("ImeVlasnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Povrsina")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Stanovi");
                });

            modelBuilder.Entity("backend.Models.Racun", b =>
                {
                    b.HasOne("backend.Models.Stan", "Stan")
                        .WithMany("RacuniZaStan")
                        .HasForeignKey("StanID");

                    b.Navigation("Stan");
                });

            modelBuilder.Entity("backend.Models.Stan", b =>
                {
                    b.Navigation("RacuniZaStan");
                });
#pragma warning restore 612, 618
        }
    }
}
